[package]
name = "ts-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
log = []

[dependencies]
bitvec = "1.0.1"
log = "0.4.21"

[dev-dependencies]
env_logger = "0.11.3"

[log.dependencies]
log = "0.4.21"
